//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Part4.InventoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InventoryService.InvService")]
    public interface InvService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvService/GetLatestQuantities", ReplyAction="http://tempuri.org/InvService/GetLatestQuantitiesResponse")]
        string GetLatestQuantities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvService/GetLatestQuantities", ReplyAction="http://tempuri.org/InvService/GetLatestQuantitiesResponse")]
        System.Threading.Tasks.Task<string> GetLatestQuantitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvService/UpdateQuantities", ReplyAction="http://tempuri.org/InvService/UpdateQuantitiesResponse")]
        string UpdateQuantities(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvService/UpdateQuantities", ReplyAction="http://tempuri.org/InvService/UpdateQuantitiesResponse")]
        System.Threading.Tasks.Task<string> UpdateQuantitiesAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvService/DecrementItemQuantity", ReplyAction="http://tempuri.org/InvService/DecrementItemQuantityResponse")]
        string DecrementItemQuantity(int itemNum, int amt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvService/DecrementItemQuantity", ReplyAction="http://tempuri.org/InvService/DecrementItemQuantityResponse")]
        System.Threading.Tasks.Task<string> DecrementItemQuantityAsync(int itemNum, int amt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvService/IncrementItemQuantity", ReplyAction="http://tempuri.org/InvService/IncrementItemQuantityResponse")]
        string IncrementItemQuantity(int itemNum, int amt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvService/IncrementItemQuantity", ReplyAction="http://tempuri.org/InvService/IncrementItemQuantityResponse")]
        System.Threading.Tasks.Task<string> IncrementItemQuantityAsync(int itemNum, int amt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InvServiceChannel : Part4.InventoryService.InvService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvServiceClient : System.ServiceModel.ClientBase<Part4.InventoryService.InvService>, Part4.InventoryService.InvService {
        
        public InvServiceClient() {
        }
        
        public InvServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetLatestQuantities() {
            return base.Channel.GetLatestQuantities();
        }
        
        public System.Threading.Tasks.Task<string> GetLatestQuantitiesAsync() {
            return base.Channel.GetLatestQuantitiesAsync();
        }
        
        public string UpdateQuantities(string data) {
            return base.Channel.UpdateQuantities(data);
        }
        
        public System.Threading.Tasks.Task<string> UpdateQuantitiesAsync(string data) {
            return base.Channel.UpdateQuantitiesAsync(data);
        }
        
        public string DecrementItemQuantity(int itemNum, int amt) {
            return base.Channel.DecrementItemQuantity(itemNum, amt);
        }
        
        public System.Threading.Tasks.Task<string> DecrementItemQuantityAsync(int itemNum, int amt) {
            return base.Channel.DecrementItemQuantityAsync(itemNum, amt);
        }
        
        public string IncrementItemQuantity(int itemNum, int amt) {
            return base.Channel.IncrementItemQuantity(itemNum, amt);
        }
        
        public System.Threading.Tasks.Task<string> IncrementItemQuantityAsync(int itemNum, int amt) {
            return base.Channel.IncrementItemQuantityAsync(itemNum, amt);
        }
    }
}
